In [1]:
import numpy as np
import tensorflow as tf

In [2]:
x_data=tf.Variable(initial_value=[[4.5,2.5], [3.1,2],[3.5,4.3],[5.2,6.2],[2.5,3.5]])
y_data=tf.Variable([[0.,1.],[1.,0.],[0.,1.],[0.,1.],[1.,0.]])

In [3]:
#X=tf.placeholder("float",shape=[5,2],name="Xm")
#graph = tf.get_default_graph()
#zz = graph.get_tensor_by_name('Xm:0')
W = tf.Variable(np.random.randn(), name='weight')
b = tf.Variable(np.random.randn(), name='bias')
pred =tf.multiply(x_data, W)+b
#with tf.variable_scope('pred', reuse=au):
    #z= tf.get_variable('pred')

z=tf.get_variable('z',initializer=pred)
#z=tf.contrib.framework.get_variables('z',shape=[5,2],initializer=pred)

In [4]:
pred=tf.argmax(pred,1)

In [5]:
ind=tf.where(tf.equal(pred,0))
#ind=tf.reshape(ind,[-1])

In [6]:
n=tf.reduce_sum(pred)

In [7]:
sess=tf.Session()
sess.run(tf.global_variables_initializer())

In [8]:
sess.run(W)

0.69036329

In [9]:
sess.run(z)

array([[ 3.24230576,  1.86157918],
       [ 2.27579713,  1.51639748],
       [ 2.55194235,  3.10423326],
       [ 3.72555995,  4.4159236 ],
       [ 1.86157918,  2.55194235]], dtype=float32)

In [10]:
sess.run(pred)

array([0, 0, 1, 1, 1], dtype=int64)

In [11]:
type(z)

tensorflow.python.ops.variables.Variable

In [12]:
sess.run(pred)

array([0, 0, 1, 1, 1], dtype=int64)

In [13]:
sess.run(ind)

array([[0],
       [1]], dtype=int64)

In [14]:
type(x_data)

tensorflow.python.ops.variables.Variable

In [18]:
a=tf.constant([[0.,0.],[0.,0.]]) 

In [19]:
c=tf.scatter_nd_update(z,ind,a)

In [20]:
sess.run(c)

array([[ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 2.55194235,  3.10423326],
       [ 3.72555995,  4.4159236 ],
       [ 1.86157918,  2.55194235]], dtype=float32)

In [21]:
loss_fun=tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=c, labels=y_data))
optimizer=tf.train.AdamOptimizer(learning_rate=0.001).minimize(loss_fun)

In [22]:
sess.run(loss_fun)

0.66882002